language: rust
dist: focal
services:
  - docker
stages:
  - lint contract
  - test contract
  - set up nctl
#  - deploy contract to nctl
jobs:
  include:
    - stage: lint contract
      name: "Clippy Lint"
      if: type IN (push) and branch =~ ^(main|develop|master|)(\/[a-zA-Z0-9]+([-_][a-zA-Z0-9]+)*)$
      script:
        - rustup component add clippy --toolchain nightly-2022-01-13-x86_64-unknown-linux-gnu
        - rustup component add rustfmt --toolchain nightly-2022-01-13-x86_64-unknown-linux-gnu
        - make prepare
        - make check-lint
    - stage: test contract
      name: "Cargo unit tests"
      if: type IN (push) and branch =~ ^(main|develop|master|)(\/[a-zA-Z0-9]+([-_][a-zA-Z0-9]+)*)$
      script:
        - make prepare
        - make test
    - stage: set up nctl
      name: "Docker Pull NCTL"
      if:
      script:
        - docker pull makesoftware/casper-nctl
        - docker run --rm -it --name mynctl -d -p 11101:11101 -p 14101:14101 -p 18101:18101 makesoftware/casper-nctl
        - source nctl-activate.sh mynctl