language: rust
dist: focal
services:
  - docker
stages:
  - lint contract
  - test contract
  - set up nctl
  - deploy contract to nctl
jobs:
  include:
    - stage: lint contract
      name: "Clippy Lint"
      if: type IN (push) and branch =~ /^(feature|develop)(\/){1,1}([a-z]){2,}([-_]){1,1}([a-zA-Z0-9])*$/gm
      script:
        - rustup component add clippy --toolchain nightly-2022-01-13-x86_64-unknown-linux-gnu
        - rustup component add rustfmt --toolchain nightly-2022-01-13-x86_64-unknown-linux-gnu
        - make prepare
        - make check-lint
    - stage: test contract
      name: "Cargo unit tests"
      if: type IN (push) and branch =~ /^(feature|develop)(\/){1,1}([a-z]){2,}([-_]){1,1}([a-zA-Z0-9])*$/gm
      script:
        - make prepare
        - make test
    - stage: set up nctl
      name: "Docker Pull NCTL"
      if: type IN (push) and branch =~ /^(feature|develop)(\/){1,1}([a-z]){2,}([-_]){1,1}([a-zA-Z0-9])*$/gm
      script:
        - docker pull makesoftware/casper-nctl
        - docker run --rm -it --name mynctl -d -p 11101:11101 -p 14101:14101 -p 18101:18101 makesoftware/casper-nctl
        - source nctl-activate.sh mynctl
    - stage: deploy contract to nctl
      name: "Docker deployment test"
      if: type IN (pull_request) and branch =~ /^(feature|main)(\/)*([a-z])*([-_])*([a-zA-Z0-9])*$/gm
      script:
        - make prepare
        - make build-contract
        - echo "deb https://repo.casperlabs.io/releases" bionic main | sudo tee -a /etc/apt/sources.list.d/casper.list
        - curl -O https://repo.casperlabs.io/casper-repo-pubkey.asc
        - sudo apt-key add casper-repo-pubkey.asc
        - sudo apt update
        - sudo apt install -y casper-client casper-node-launcher jq
        - docker pull makesoftware/casper-nctl
        - docker run --rm -it --name mynctl -d -p 11101:11101 -p 14101:14101 -p 18101:18101 makesoftware/casper-nctl
        - source nctl-activate.sh mynctl
        - nctl-view-user-secret-key user=1 > user1_secret_key.pem
        - casper-client put-deploy \
          --node-address  http://localhost:11101/rpc \
          --chain-name casper-net-1 \
          --secret-key user1_secret_key.pem \
          --payment-amount 30000000000 \
          --session-path contract/target/wasm32-unknown-unknown/release/inventory-count.wasm